import './globals.css'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ 
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  )
}
